### ISSUE TITLE
Exception with HydraRegistrations

### ISSUE THREAD

**Issue by colin-young** [wikibus/Argolis#5]
Using the NuGet package, I'm seeing `Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Hydra.Nancy.HydraRegistrations ---> System.MissingMethodException: Method not found: 'Void Nancy.Bootstrapper.Registrations..ctor()'.
   at Hydra.Nancy.HydraRegistrations..ctor()`

I'm thinking it has to do with Nancy `Registrations` no longer providing a parameterless constructor (since 5e36a5b8ef3d7f919cef8f5bf889af83f38b1c99). At least, when I try to follow the setup in the readme here, I need to use:

    public ArgolisRegistrations(ITypeCatalog typeCatalog) : base(typeCatalog) { ... }

rather than

    public ArgolisRegistrations() { ... }

[HydraRegistrations.cs](https://github.com/wikibus/Argolis/blob/master/src/Lernaean.Hydra.Nancy/HydraRegistrations.cs) is still trying to use the parameterless constructor.

Does that seem like a reasonable conclusion, or am I going down the wrong path? Those changes have been in Nancy for quite a while now, and are included in the version listed in the Argolis dependencies (2.0.0-barneyrubble).

**Comment by tpluscode** [comment]
Which version of Argolis and Nancy do you have installed? Looks like you have incompatible packages.

Argolis `0.2.1-unstable0203` should already use Nancy 2.0+ via Nancy.Rdf 0.3.0

**Comment by colin-young** [comment]
From project.assets.json:

- Nancy/2.0.0-barneyrubble
- Nancy.Rdf/0.3.0
- Rdf.Vocabularies/1.1.1
- Argolis/0.2.1-unstable0203

Which branch is the `0.2.1-unstable0203` NuGet package built from? I see `develop` has the necessary update to the [HydraRegistrations.cs](https://github.com/wikibus/Argolis/blob/develop/src/Lernaean.Hydra.Nancy/HydraRegistrations.cs), but when I look at the dissassembly from the NuGet package, I see:

    public HydraRegistrations()
    {
      base.\u002Ector();
      ...
    }

Maybe we just need a new build of the NuGet package? I'm stuck behind a corporate firewall so can't clone from GitHub

**Comment by tpluscode** [comment]
This is most curious. I'll look into it tomorrow. I've only ever referenced theses packages in old skool `.csproj` although I doubt it's a factor

**Comment by colin-young** [comment]
Yeah, I wouldn't expect that to affect things. I set up a virtual desktop on Azure last night, and was able to successfully build the develop branch, so I should be able to contribute more productively now

**Comment by tpluscode** [comment]
Huh, it's actually just before I started upgrading to Nancy 2.0. In fact, build `unstable-204` is the first one. I've just pushed a new prerelease `211` package to NuGet. Please try that in a few minutes.

**Comment by colin-young** [comment]
That package seems to have fixed it.
