### ISSUE TITLE
How do I wire up with Autofac bootstrapper?

### ISSUE THREAD

**Issue by colin-young** [wikibus/Argolis#7]
Dumb question, but how do I wire `Argolis` up if I'm using the `Autofac bootstrapper` for Nancy? I've tried (using the code from the Readme):

    builder.RegisterType<Bootstrapper>().As<INancyBootstrapper>();
    builder.RegisterType<ArgolisRegistrations>().As<IRegistrations>();
    builder.RegisterType<HydraDocumentationSettings>().As<IHydraDocumentationSettings>();
    builder.RegisterType<AssembliesToScanForSupportedTypes>().As<IDocumentedTypeSelector>();

But there's a 404 on my endpoint, and no link in any responses. I do hit a breakpoint in the `ArgolisRegistrations` constructor, but otherwise it doesn't seem to be doing anything.

Any pointers appreciated. I'm pretty new to Nancy (so maybe throwing `Autofac` and `Argolis` into the mix isn't the best idea...)

When I add a dependency on `IRegistrations` to my main module, I'm able to get:

```
{
  "collectionTypeRegistrations": [],
  "instanceRegistrations": [
    {
      "implementation": {
        "documentationPath": "api",
        "entryPoint": {
          "value": "http://1511-dev14.ad.XXXX.com:5000/entrypoint"
        }
      },
      "lifetime": 1,
      "registrationType": "Hydra.IHydraDocumentationSettings"
    }
  ],
  "typeRegistrations": []
}
```

But that's really just telling me `Autofac` knows about it.

**Comment by tpluscode** [comment]
I'm using Autofac myself so it definitely works. Nancy gives you some abstraction over containers and Argolis doesn't really care which one you use. You can only have problems with mixed lifecycles of your components.

For a simple setup though you shouldn't even have to touch Autofac builder at all. `Bootstrapper` and `IRegistrations` is discovered by Nancy automatically (regardless of DI container), `IDocumentTypeSelector` is [discovered by Argolis](https://github.com/wikibus/Argolis/blob/master/src/Lernaean.Hydra.Nancy/HydraRegistrations.cs#L33). What's left is the `IHydraDocumentationSettings`, which in the readme I register in `ArgolisRegistrations`.

Let me know if that helps

**Comment by colin-young** [comment]
I'm pretty sure the problem is me, and that I'm just missing something simple. The documentation for the Autofac bootstrapper is pretty minimal and I figured if anyone would know how to do it it would be you.

Unfortunately I've got several things being injected by Autofac so it's not so simple to just pull it out.

**Comment by tpluscode** [comment]
It's bad sign that you're not getting the `hydra:ApiDocumentation` link header in responses. It would indicate that [`HydraDocumentationStartup`](https://github.com/wikibus/Argolis/blob/master/src/Lernaean.Hydra.Nancy/HydraDocumentationStartup.cs) is not firing.

Do you have anything in your Nancy bootstrapper that could interfere with `IApplicationStartup` being run? What happens if you create an implementation in your code but not add to Autofac. Will it get constructed and executed?

**Comment by colin-young** [comment]
This is my entire bootstrapper:

    public class Bootstrapper : AutofacNancyBootstrapper
    {
        readonly ILifetimeScope _container;

        public Bootstrapper(ILifetimeScope container)
        {
            _container = container;
        }

        protected override ILifetimeScope GetApplicationContainer()
        {
            return _container;
        }
    }

And set up as `app.UseNancy(options => { options.Bootstrapper = new Bootstrapper(container);  });`

Everything starts up and wires up if I remove all the Nancy-specific stuff (from the first post), except for the missing docs. I'm going to see if I can get a breakpoint into `IApplicationStartup` or `HydraDocumentationStartup` and see if that explains anything.

**Comment by colin-young** [comment]
I told you it was something simple -- turns out I had somehow removed `Agolis.Nancy` from my references, but left `Argolis`. Only discovered that after using DotPeek to find the startup and realizing that I wasn't referencing that assembly, even though it was on my system.

Now I've got a 500 internal service error to deal with, but those I know how to handle. Thanks for the assistance.
